paths:
  /blogs:
    get:
      tags: [Blogs]
      summary: Get list a blogs
      parameters: 
        - $ref: '#/components/parameters/SearchBlogNameTermQueryParam'
        - $ref: '#/components/parameters/SortDirectionQueryParam'
        - $ref: '#/components/parameters/PageSizeQueryParam'
        - $ref: '#/components/parameters/PageNumberQueryParam'
        - $ref: '#/components/parameters/BlogsSortByQueryParam'
      responses: 
        '200':
          description: Successful
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ViewBlogsPaginationSchema'

    post:
      tags: [Blogs]
      summary: Create a new blog
      security:
        - BasicAuth: []
      requestBody: 
        description: Data for create blog
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/InputBlogSchema'
      responses: 
        '201':
          description: Successfully create blogs
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ViewBlogSchema'
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          description: Unauthorized

  /blogs/{id}/posts:
    get:
      tags: [Blogs]
      summary: Get posts for blog
      parameters: 
        - $ref: '#/components/parameters/BlogIdPathParam'
        - $ref: '#/components/parameters/PostsSortByQueryParam'
        - $ref: '#/components/parameters/SortDirectionQueryParam'
        - $ref: '#/components/parameters/PageSizeQueryParam'
        - $ref: '#/components/parameters/PageNumberQueryParam'
      responses: 
        '200':
          $ref: '#/components/responses/PaginatedPostsResponse'
        '404':
          description: Blog not found
    post:
      tags: [Blogs]
      summary: Create post for blog
      security:
        - BasicAuth: []
      parameters: 
        - $ref: '#/components/parameters/BlogIdPathParam'
      requestBody: 
        description: Data for create post
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/InputBlogPostSchema'
      responses: 
        '201':
          $ref: '#/components/responses/SuccessfullyCreatePost'
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Blog not found  

  /blogs/{id}:
    get:
      tags: [Blogs]
      summary: Get blog by id
      parameters: 
        - $ref: '#/components/parameters/BlogIdPathParam'
      responses: 
        '200':
          description: Successful
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ViewBlogSchema'
        '404':
          description: Blog not found
    put:
      tags: [Blogs]
      summary: Update blog by id
      security:
        - BasicAuth: []
      parameters: 
        - $ref: '#/components/parameters/BlogIdPathParam'
      requestBody: 
        description: Data for update blog
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/InputBlogSchema'
      responses: 
        '204':
          description: Successfully update blog
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Blog not found
    delete:
      tags: [Blogs]
      summary: Delete blog by id
      security:
        - BasicAuth: []
      parameters: 
        - $ref: '#/components/parameters/BlogIdPathParam'
      responses: 
        '204':
          description: Successfully delete blog
        '401':
          description: Unauthorized
        '404':
          description: Blog not found


components: 
  schemas: 
    ViewBlogSchema:
      type: object
      required: 
        - id
        - name
        - description
        - websiteUrl
        - createdAt
        - isMembership
      properties: 
        id:
          type: string
          description: Mongo ObjectId format
        name:
          type: string
        description:
          type: string
        websiteUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        isMembership:
          type: boolean
          default: false
          
    ViewBlogsPaginationSchema:
      allOf:
        - $ref: '#/components/schemas/BasePaginatorSchema'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ViewBlogSchema'

    InputBlogSchema:
      type: object
      required: 
        - name
        - description
        - websiteUrl
      properties: 
        name:
          type: string
          maxLength: 15
        description:
          type: string
          maxLength: 500
        websiteUrl:
          type: string
          maxLength: 100

    InputBlogPostSchema:
      type: object
      required: 
        - title
        - shortDescription
        - content
      properties: 
        title:
          type: string
        shortDescription:
          type: string
        content:
          type: string

    BlogsSortFieldSchema:
      type: string
      description: available fields for blogs sorting
      enum: 
        - name
        - createdAt
      default: createdAt
    
  parameters:
    BlogIdPathParam:
      in: path
      name: id
      required: true
      description: Mongo ObjectId format unique identifier of the blog
      schema:
        type: string
        example: '696c891bdfcde0419df1674d'

    SearchBlogNameTermQueryParam:
      in: query
      name: searchNameTerm
      description: blog name substring for searching
      schema:
        type: string
        example: Node JS tutorial
    
    BlogsSortByQueryParam:
      in: query
      name: sortBy
      description: sorting blog field name
      schema: 
        allOf: 
          - $ref: '#/components/schemas/BlogsSortFieldSchema'
        type: string
        default: createdAt