components: 
  schemas: 
    ViewCommentSchema:
      type: object
      required: 
        - id
        - content
        - commentatorInfo
        - createdAt
      properties: 
        id:
          type: string
        content:
          type: string
        commentatorInfo:
          type: object
          properties:
            userId:
              type: string
            userLogin:
              type: string
        createdAt:
          type: string
          format: date-time

    InputCommentSchema:
      type: object
      required: 
        - content
      properties: 
        content:
          type: string
          minLength: 30
          maxLength: 300