export const EMAIL_SERVICE_USER_EMAIL = process.env.EMAIL_SERVICE_USER_EMAIL;
export const EMAIL_SERVICE_PASSWORD = process.env.EMAIL_SERVICE_PASSWORD;
export const EMAIL_SERVICE_USER_LOGIN = process.env.EMAIL_SERVICE_USER_LOGIN;
export const EMAIL_CONFORMATION_CODE_LIFETIME_IN_MINUTES =
  Number(process.env.EMAIL_CONFORMATION_CODE_LIFETIME_IN_MINUTES) || 10;
