export const EMAIL_SERVICE_USER_EMAIL = process.env.EMAIL_SERVICE_USER_EMAIL;
export const EMAIL_SERVICE_PASSWORD = process.env.EMAIL_SERVICE_PASSWORD;
export const EMAIL_SERVICE_USER_LOGIN = process.env.EMAIL_SERVICE_USER_LOGIN;