paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: Login user
      requestBody: 
        description: User credentials
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/InputLoginUserSchema'
      responses: 
        '200':
          description: Successfully login user
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/AccessTokenSchema'
          headers:
            Set-Cookie:
              $ref: '#/components/headers/RefreshTokenCookie'
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          description: Unauthorized

  /auth/me:
    get:
      tags: [Auth]
      summary: Get user info by access token
      security: 
        - BearerAuth: []
      responses: 
        '200':
          description: User info
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/ViewUserMeSchema'
        '401':
          description: Unauthorized
        '404':
          description: User not found

  /auth/registration:
    post:
        tags: [Auth]
        summary: User self registration
        requestBody: 
            description: User credentials
            content:
                application/json: 
                  schema: 
                    $ref: '#/components/schemas/InputUserSchema' 
        responses: 
            '204':
                description: User successfully registered
            '400': 
                $ref: '#/components/responses/ValidationErrorResponse'

  /auth/registration-email-resending:
    post:
        tags: [Auth]
        summary: Resend email confirmation code
        requestBody: 
            description: User email
            content:
                application/json: 
                  schema: 
                    $ref: '#/components/schemas/InputResendingEmailConfirmationSchema' 
        responses: 
            '204':
                description: Email successfully resend
            '400': 
                $ref: '#/components/responses/ValidationErrorResponse'

  /auth/registration-confirmation:
    post:
        tags: [Auth]
        summary: Confirm email
        requestBody: 
            description: User confirmation code
            content:
                application/json: 
                  schema: 
                    $ref: '#/components/schemas/InputRegistrationConfirmationSchema' 
        responses: 
            '204':
                description: Email successfully confirmed
            '400': 
                $ref: '#/components/responses/ValidationErrorResponse'

  /auth/refresh-token:
    post:
      tags: [Auth]
      summary: Refresh access and refresh tokens pair
      security:
        - RefreshToken: []
      responses:
        '200':
          description: Tokens successfully refresh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenSchema'
          headers:
            Set-Cookie:
              $ref: '#/components/headers/RefreshTokenCookie'
        '401':
          description: Unauthorized

components: 
  schemas: 
    InputLoginUserSchema:
      type: object
      required: 
        - loginOrEmail
        - password
      properties: 
        loginOrEmail:
          oneOf:
            - type: string
              minLength: 3
              maxLength: 10
              pattern: ^[a-zA-Z0-9_-]*$
              description: User login
            - type: string
              format: email
              pattern: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
              description: User email
        password:
          type: string

    AccessTokenSchema:
      type: object
      required: 
        - accessToken
      properties: 
        accessToken:
          type: string
          description: JWT access token. Lifetime 10 seconds

    InputResendingEmailConfirmationSchema:
      type: object
      required: 
        - email
      properties: 
        email:
          type: string
          format: email
          pattern: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$

    InputRegistrationConfirmationSchema:
      type: object
      required: 
        - code
      properties: 
        code:
          type: string

  parameters:
    UserIdPathParam:
      in: path
      name: id
      required: true
      description: Mongo ObjectId format unique identifier of the user
      schema:
        type: string
        example: '696c891bdfcde0419df1674d'
    
    UsersSortByQueryParam:
      in: query
      name: sortBy
      description: sorting users field name
      schema: 
        allOf: 
          - $ref: '#/components/schemas/UsersSortFieldSchema'
        type: string
        default: createdAt
    
    SearchLoginTermQueryParam:
      in: query
      name: searchLoginTerm
      description: login substring for searching
      schema:
        type: string
        example: Andr

    SearchEmailTermQueryParam:
      in: query
      name: searchEmailTerm
      description: email substring for searching
      schema:
        type: string
        example: andrew@

  headers:
    RefreshTokenCookie:
      description: Refresh token in HTTP-only cookie. Lifetime 20 seconds
      schema:
        type: string
        example: "refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure;"